services:
  rustfs:
    image: rustfs/rustfs:1.0.0
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './.temp/rustfs:/data'
    environment:
      - RUSTFS_ACCESS_KEY=rustfs_username
      - RUSTFS_SECRET_KEY=rustfs_password
      - RUSTFS_CONSOLE_ENABLE=true

  azure-blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    volumes:
      - ./.temp/azurite:/workspace